#ifndef _LCOM_I8042_H_
#define _LCOM_I8042_H_

#include <lcom/lcf.h>

#define KEYBOARD_IRQ 1

#define KBC_OUT_BUF 0x60
#define KBC_ST_REG 0x64
#define KBC_CMD_REG 0x64

#define ESC_MAKE_CODE 0x81

#define BREAK_CODE_BIT 1 << 7
#define MULTIBYTE_CODE 0xE0

#define KBC_OBF 1 << 0
#define KBC_IBF 1 << 1
#define KBC_AUX 1 << 5
#define KBC_TIMEOUT_ERR 1 << 6
#define KBC_PARITY_ERR 1 << 7

// FOR CONFIGURATION PURPOSES
#define KBC_ENABLE_INT 0xAE
#define KBC_DISABLE_INT 0xAD

#define WAIT_KBC 100

#define W_MAKE_CODE 0x11
#define A_MAKE_CODE 0x1E
#define S_MAKE_CODE 0x1F
#define D_MAKE_CODE 0x20

#define ENTER_MAKE_CODE 0x1C

#define KBC_OUT_BUF 0x60 // PORT FOR OUTPUT AND INPUT REGISTERS
#define KBC_IN_BUF 0x60

#define KBC_COMMAND_PORT 0x64 // PORT FOR STATUS AND COMMAND REGISTER
#define KBC_STATUS_PORT 0x64

#define KBC_PAR_ERR BIT(7)
#define KBC_TO_ERR BIT(6)
#define KBC_AUX_BYTE BIT(5)

#define MAX_NUM_TRIES 10
// COMMAND BYTE
// RESPONSIBLE FOR MANAGING INTERRUPTS AND SOME INTERFACES ASWELL
#define DISABLE_MOUSE_INTERFACE BIT(5)
#define DISABLE_KEYBOARD_INTERFACE BIT(4)
#define ENABLE_OBF_INT_MOUSE BIT(1)
#define ENABLE_OBF_INT_KEYBOARD BIT(0)

//DELAY
#define DELAY_US 20000



// MOUSE DATA PACKET 
#define MOUSE_Y_OVERFLOW BIT(7)
#define MOUSE_X_OVERFLOW BIT(6)
#define MOUSE_MSB_Y_DELTA BIT(5)
#define MOUSE_MSB_X_DELTA BIT(4)
#define MOUSE_MIDDLE_BUTTON BIT(2)
#define MOUSE_RIGHT_BUTTON BIT(1)
#define MOUSE_LEFT_BUTTON BIT(0)

#define MOUSE_IRQ 0x0C

// MOUSE RELATED KBC COMMANDS
#define KBC_MOUSE_COMMAND 0xD4
#define MOUSE_READ_COMMAND_BYTE 0x20
#define MOUSE_WRITE_COMMAND_BYTE 0x60

// MOUSE COMMANDS
#define MOUSE_DISABLE_DATA_REPORTING 0xF5
#define MOUSE_ENABLE_DATA_REPORTING 0xF4

// MOUSE RESPONSES
#define MOUSE_NO_RESPONSE 0x00
#define MOUSE_ACK 0xFA
#define MOUSE_NACK 0xFE
#define MOUSE_ERROR 0xFC



#endif /* _LCOM_I8042_H_ */

