/* XPM sections generated automatically */
#ifndef PACMAN2_XPM_H
#define PACMAN2_XPM_H

static const char* pacman2_0[] = {
  "16 16 3 1",
  "A c #000000",
  "B c None",
  "C c #FFFF00",
  "BBBBBBBBBBBBBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBCCCCCCCCCBBBB",
  "BBCCCCCCCCCCCBBB",
  "BBCCCCCCCCCCCBBB",
  "BCCCCCCCCCCBBBBB",
  "BCCCCCCCBBBBBBBB",
  "BCCCCBBBBBBBBBBB",
  "BCCCCCCCBBBBBBBB",
  "BCCCCCCCCCCBBBBB",
  "BBCCCCCCCCCCCBBB",
  "BBCCCCCCCCCCCBBB",
  "BBBCCCCCCCCCBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
};

static const char* pacman2_1[] = {
  "16 16 3 1",
  "A c #000000",
  "B c None",
  "C c #FFFF00",
  "BBBBBBBBBBBBBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBCCCCCCCCCBBBB",
  "BBCCCCCCCCCCCBBB",
  "BBCCCCCCCCCCCBBB",
  "BBBBCCCCCCCCCCBB",
  "BBBBBBBCCCCCCCBB",
  "BBBBBBBBBBCCCCBB",
  "BBBBBBBCCCCCCCBB",
  "BBBBCCCCCCCCCCBB",
  "BBCCCCCCCCCCCBBB",
  "BBCCCCCCCCCCCBBB",
  "BBBCCCCCCCCCBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
};

static const char* pacman2_2[] = {
  "16 16 3 1",
  "A c #000000",
  "B c None",
  "C c #FFFF00",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBCCBBBBBCCBBBB",
  "BBCCCBBBBBCCCBBB",
  "BBCCCCBBBCCCCBBB",
  "BCCCCCBBBCCCCCBB",
  "BCCCCCBBBCCCCCBB",
  "BCCCCCCBCCCCCCBB",
  "BCCCCCCBCCCCCCBB",
  "BCCCCCCCCCCCCCBB",
  "BBCCCCCCCCCCCBBB",
  "BBCCCCCCCCCCCBBB",
  "BBBCCCCCCCCCBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
};

static const char* pacman2_3[] = {
  "16 16 3 1",
  "A c #000000",
  "B c None",
  "C c #FFFF00",
  "BBBBBBBBBBBBBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBCCCCCCCCCBBBB",
  "BBCCCCCCCCCCCBBB",
  "BBCCCCCCCCCCCBBB",
  "BCCCCCCCCCCCCCBB",
  "BCCCCCCBCCCCCCBB",
  "BCCCCCCBCCCCCCBB",
  "BCCCCCBBBCCCCCBB",
  "BCCCCCBBBCCCCCBB",
  "BBCCCCBBBCCCCBBB",
  "BBCCCBBBBBCCCBBB",
  "BBBCCBBBBBCCBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
};

static const char* const*pacman2[] = {
  pacman2_0,
  pacman2_1,
  pacman2_2,
  pacman2_3,
};

#endif /* PACMAN2_XPM_H */
