/* XPM sections generated automatically */
#ifndef PACMAN2_XPM_H
#define PACMAN2_XPM_H

static char *section_0[] = {
  "16 16 3 1",
  "A c #000000",
  "B c None",
  "C c #FFFF00",
  "BBBBBBBBBBBBBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBCCCCCCCCCBBBB",
  "BBCCCCCCCCCCCBBB",
  "BBCCCCCCCCCCCBBB",
  "BCCCCCCCCCCBBBBB",
  "BCCCCCCCBBBBBBBB",
  "BCCCCBBBBBBBBBBB",
  "BCCCCCCCBBBBBBBB",
  "BCCCCCCCCCCBBBBB",
  "BBCCCCCCCCCCCBBB",
  "BBCCCCCCCCCCCBBB",
  "BBBCCCCCCCCCBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
};

static char *section_1[] = {
  "16 16 3 1",
  "A c #000000",
  "B c None",
  "C c #FFFF00",
  "BBBBBBBBBBBBBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBCCCCCCCCCBBBB",
  "BBCCCCCCCCCCCBBB",
  "BBCCCCCCCCCCCBBB",
  "BBBBCCCCCCCCCCBB",
  "BBBBBBBCCCCCCCBB",
  "BBBBBBBBBBCCCCBB",
  "BBBBBBBCCCCCCCBB",
  "BBBBCCCCCCCCCCBB",
  "BBCCCCCCCCCCCBBB",
  "BBCCCCCCCCCCCBBB",
  "BBBCCCCCCCCCBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
};

static char *section_2[] = {
  "16 16 3 1",
  "A c #000000",
  "B c None",
  "C c #FFFF00",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBCCBBBBBCCBBBB",
  "BBCCCBBBBBCCCBBB",
  "BBCCCCBBBCCCCBBB",
  "BCCCCCBBBCCCCCBB",
  "BCCCCCBBBCCCCCBB",
  "BCCCCCCBCCCCCCBB",
  "BCCCCCCBCCCCCCBB",
  "BCCCCCCCCCCCCCBB",
  "BBCCCCCCCCCCCBBB",
  "BBCCCCCCCCCCCBBB",
  "BBBCCCCCCCCCBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
};

static char *section_3[] = {
  "16 16 3 1",
  "A c #000000",
  "B c None",
  "C c #FFFF00",
  "BBBBBBBBBBBBBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBCCCCCCCCCBBBB",
  "BBCCCCCCCCCCCBBB",
  "BBCCCCCCCCCCCBBB",
  "BCCCCCCCCCCCCCBB",
  "BCCCCCCBCCCCCCBB",
  "BCCCCCCBCCCCCCBB",
  "BCCCCCBBBCCCCCBB",
  "BCCCCCBBBCCCCCBB",
  "BBCCCCBBBCCCCBBB",
  "BBCCCBBBBBCCCBBB",
  "BBBCCBBBBBCCBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
};

static char **xpm_sections[] = {
  section_0,
  section_1,
  section_2,
  section_3,
};

#endif /* PACMAN2_XPM_H */
