/* XPM sections generated automatically */
#ifndef PACMAN_XPM_H
#define PACMAN_XPM_H

static const char* pacman_0[] = {
  "16 16 3 1",
  "A c #000000",
  "B c None",
  "C c #FFFF00",
  "BBBBBBBBBBBBBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBCCCCCCCBBBBBB",
  "BBCCCCCCCBBBBBBB",
  "BBCCCCCCBBBBBBBB",
  "BCCCCCCBBBBBBBBB",
  "BCCCCCBBBBBBBBBB",
  "BCCCCBBBBBBBBBBB",
  "BCCCCCBBBBBBBBBB",
  "BCCCCCCBBBBBBBBB",
  "BBCCCCCCBBBBBBBB",
  "BBCCCCCCCBBBBBBB",
  "BBBCCCCCCCBBBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
};

static const char* pacman_1[] = {
  "16 16 3 1",
  "A c #000000",
  "B c None",
  "C c #FFFF00",
  "BBBBBBBBBBBBBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBBBCCCCCCCBBBB",
  "BBBBBBCCCCCCCBBB",
  "BBBBBBBCCCCCCBBB",
  "BBBBBBBBCCCCCCBB",
  "BBBBBBBBBCCCCCBB",
  "BBBBBBBBBBCCCCBB",
  "BBBBBBBBBCCCCCBB",
  "BBBBBBBBCCCCCCBB",
  "BBBBBBBCCCCCCBBB",
  "BBBBBBCCCCCCCBBB",
  "BBBBBCCCCCCCBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
};

static const char* pacman_2[] = {
  "16 16 3 1",
  "A c #000000",
  "B c None",
  "C c #FFFF00",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BCCBBBBBBBBBCCBB",
  "BCCCBBBBBBBCCCBB",
  "BCCCCBBBBBCCCCBB",
  "BCCCCCBBBCCCCCBB",
  "BCCCCCCBCCCCCCBB",
  "BBCCCCCCCCCCCBBB",
  "BBCCCCCCCCCCCBBB",
  "BBBCCCCCCCCCBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
};

static const char* pacman_3[] = {
  "16 16 3 1",
  "A c #000000",
  "B c None",
  "C c #FFFF00",
  "BBBBBBBBBBBBBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBCCCCCCCCCBBBB",
  "BBCCCCCCCCCCCBBB",
  "BBCCCCCCCCCCCBBB",
  "BCCCCCCBCCCCCCBB",
  "BCCCCCBBBCCCCCBB",
  "BCCCCBBBBBCCCCBB",
  "BCCCBBBBBBBCCCBB",
  "BCCBBBBBBBBBCCBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
};

static const char* const* pacman[] = {
  pacman_0,
  pacman_1,
  pacman_2,
  pacman_3,
};

#endif /* PACMAN_XPM_H */
