/* XPM sections generated automatically */
#ifndef PACMAN_XPM_H
#define PACMAN_XPM_H

static char *section_0[] = {
  "16 16 3 1",
  "A c #000000",
  "B c None",
  "C c #FFFF00",
  "BBBBBBBBBBBBBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBCCCCCCCBBBBBB",
  "BBCCCCCCCBBBBBBB",
  "BBCCCCCCBBBBBBBB",
  "BCCCCCCBBBBBBBBB",
  "BCCCCCBBBBBBBBBB",
  "BCCCCBBBBBBBBBBB",
  "BCCCCCBBBBBBBBBB",
  "BCCCCCCBBBBBBBBB",
  "BBCCCCCCBBBBBBBB",
  "BBCCCCCCCBBBBBBB",
  "BBBCCCCCCCBBBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
};

static char *section_1[] = {
  "16 16 3 1",
  "A c #000000",
  "B c None",
  "C c #FFFF00",
  "BBBBBBBBBBBBBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBBBCCCCCCCBBBB",
  "BBBBBBCCCCCCCBBB",
  "BBBBBBBCCCCCCBBB",
  "BBBBBBBBCCCCCCBB",
  "BBBBBBBBBCCCCCBB",
  "BBBBBBBBBBCCCCBB",
  "BBBBBBBBBCCCCCBB",
  "BBBBBBBBCCCCCCBB",
  "BBBBBBBCCCCCCBBB",
  "BBBBBBCCCCCCCBBB",
  "BBBBBCCCCCCCBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
};

static char *section_2[] = {
  "16 16 3 1",
  "A c #000000",
  "B c None",
  "C c #FFFF00",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BCCBBBBBBBBBCCBB",
  "BCCCBBBBBBBCCCBB",
  "BCCCCBBBBBCCCCBB",
  "BCCCCCBBBCCCCCBB",
  "BCCCCCCBCCCCCCBB",
  "BBCCCCCCCCCCCBBB",
  "BBCCCCCCCCCCCBBB",
  "BBBCCCCCCCCCBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
};

static char *section_3[] = {
  "16 16 3 1",
  "A c #000000",
  "B c None",
  "C c #FFFF00",
  "BBBBBBBBBBBBBBBB",
  "BBBBBCCCCCBBBBBB",
  "BBBCCCCCCCCCBBBB",
  "BBCCCCCCCCCCCBBB",
  "BBCCCCCCCCCCCBBB",
  "BCCCCCCBCCCCCCBB",
  "BCCCCCBBBCCCCCBB",
  "BCCCCBBBBBCCCCBB",
  "BCCCBBBBBBBCCCBB",
  "BCCBBBBBBBBBCCBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBB",
};

static char **xpm_sections[] = {
  section_0,
  section_1,
  section_2,
  section_3,
};

#endif /* PACMAN_XPM_H */
